// src/views/admin/class/modal/AddReserveMemberModal.vue
<template>
  <CModal
    class="close"
    :visible="modalStatus"
    @close="() => {modalStatus = false}"
  >
    <CModalHeader class="modal-header">
      <CModalTitle>회원 추가</CModalTitle>
    </CModalHeader>
    <CModalBody>
      <CTabs active-tab="activeTab">
        <!-- 탭 네비게이션 -->
        <CNav variant="tabs" class="mb-3">
          <CNavItem>
            <CNavLink :active="activeTab === 'realName'" @click="setActiveTab('realName')">
              이름으로 찾기
            </CNavLink>
          </CNavItem>
          <CNavItem>
            <CNavLink :active="activeTab === 'email'" @click="setActiveTab('email')">
              이메일로 찾기
            </CNavLink>
          </CNavItem>
          <CNavItem>
            <CNavLink :active="activeTab === 'phone'" @click="setActiveTab('phone')">
              전화번호로 찾기
            </CNavLink>
          </CNavItem>
        </CNav>

        <!-- 탭 컨텐츠 -->
        <CTabContent>
          <!-- 이름 검색 탭 -->
          <CTabPane v-if="activeTab === 'realName'" visible>
            <CRow class="align-items-center g-2">
              <CCol md="2">이름</CCol>
              <CCol md="8">
                <CFormInput 
                  v-model="searchName"
                  type="text"
                  id="nameInput"
                  placeholder="이름을 입력하세요."
                />
              </CCol>
              <CCol md="2">
                <CButton color="primary" class="search-button" @click="searchUserByName">
                  검색
                </CButton>
              </CCol>
            </CRow>
          </CTabPane>

          <!-- 이메일 검색 탭 -->
          <CTabPane v-if="activeTab === 'email'" visible>
            <CRow class="align-items-center g-2">
              <CCol md="2">이메일</CCol>
              <CCol md="8">
                <CFormInput 
                  v-model="searchEmail"
                  type="text"
                  id="emailInput"
                  placeholder="이메일을 입력하세요."
                />
              </CCol>
              <CCol md="2">
                <CButton color="primary" class="search-button" @click="searchUserByEmail">
                  검색
                </CButton>
              </CCol>
            </CRow>
          </CTabPane>

          <!-- 전화번호 검색 탭 -->
          <CTabPane v-if="activeTab === 'phone'" visible>
            <CRow class="align-items-center g-2">
              <CCol md="2">전화번호</CCol>
              <CCol md="8">
                <CFormInput 
                  v-model="searchPhone"
                  type="text"
                  id="phoneInput"
                  placeholder="핸드폰 번호를 입력하세요.(- 제외)"
                />
              </CCol>
              <CCol md="2">
                <CButton color="primary" class="search-button" @click="searchUserByPhone">
                  검색
                </CButton>
              </CCol>
            </CRow>
          </CTabPane>
        </CTabContent>
      </CTabs>

      <!-- Results Area -->
      <div class="mt-3">
        <!-- Single user -->
        <CCard v-if="user" class="border-dark">
          <CCardHeader class="bg-light fw-bold">검색 결과</CCardHeader>
          <CCardBody>
            <CListGroup flush>
              <CListGroupItem><strong>이름:</strong> {{ user.realName }} <span v-if="isClassMember(user)"><strong>[이미 추가된 회원]</strong></span></CListGroupItem>
              <CListGroupItem><strong>연락처:</strong> {{ user.phone }}</CListGroupItem>
              <CListGroupItem><strong>이메일:</strong> {{ user.email }}</CListGroupItem>
            </CListGroup>
          </CCardBody>
          <CCardFooter class="text-end">
            <CButton color="success" @click="addMember(user)" :disabled="isClassMember(user)">추가</CButton>
          </CCardFooter>
        </CCard>

        <!-- Multiple users -->
        <template v-else-if="users?.length > 0">
          <CCard
            v-for="(u, index) in users"
            :key="index"
            class="border-dark mb-3"
          >
            <CCardHeader class="bg-light fw-bold">검색 결과</CCardHeader>
            <CCardBody>
              <CListGroup flush>
                <CListGroupItem><strong>이름:</strong> {{ u.realName }} <span v-if="isClassMember(u)"><strong>[이미 추가된 회원]</strong></span></CListGroupItem>
                <CListGroupItem><strong>연락처:</strong> {{ u.phone }}</CListGroupItem>
                <CListGroupItem><strong>이메일:</strong> {{ u.email }}</CListGroupItem>
              </CListGroup>
            </CCardBody>
            <CCardFooter class="text-end">
              <CButton color="success" @click="addMember(u)" :disabled="isClassMember(u)">추가</CButton>
            </CCardFooter>
          </CCard>
        </template>
      </div>
    </CModalBody>

    <CModalFooter>
      <CButton color="danger" @click="() => {modalStatus = false}">
        닫기
      </CButton>
    </CModalFooter>
  </CModal>
  <wod-confirmation-modal ref="wodConfirmationModalRef" />
</template>

<script>
import {ref} from "vue"
import { useStore } from "vuex"
import {calculateAge, convertGenderToKorean} from "@/views/admin/util/member"
import WodConfirmationModal from "@/views/admin/class/modal/WodConfirmationModal.vue";

export default {
  components: {WodConfirmationModal},
    props: {
        classmembers: {
        type: Array,
        required: true,
        }
    },
  setup(props, context) {
    const boxName = ref(localStorage.getItem('boxName') || '');
    const store = useStore();
    const modalStatus = ref(false);
    const activeTab = ref('realName');
    const searchName = ref("");
    const searchEmail = ref("");
    const searchPhone = ref("");
    const user = ref(null);
    const users = ref([]); //유저가 여러명일 경우
    const wodConfirmationModalRef = ref(null);
    const classId = ref("")
    const date = ref("")

    const getAge = (birthDate) => {
      return calculateAge(birthDate)
    }

    const getGender = (gender) => {
      return convertGenderToKorean(gender)
    }

    const setActiveTab = (tab) => {
      activeTab.value = tab;
      user.value = '';
      users.value = [];
      searchName.value = '';
      searchEmail.value = '';
      searchPhone.value = '';
    }

    const searchUserByName = async () => {
      console.log(searchName, "searchname")
      if (!searchName.value.trim()) {
        alert("이름을 입력하세요.");
        return;
      }

      try {
        // Call Vuex action to get user data
        const userData = await store.dispatch("getWodUserByName", { realName: searchName.value, boxName: boxName.value});
        if (userData) {
          users.value = userData;
          user.value = null;
        } else {
          users.value = [];
          user.value = null;
          console.warn("⚠️ Warning: User document does not exist.");
          alert("해당 사용자를 찾을 수 없습니다.");
        }
      } catch (error) {
        console.error("❌ Error fetching user:", error);
        alert("사용자 검색 중 오류가 발생했습니다.");
      }
    };

    const searchUserByEmail = async () => {
      console.log(searchEmail, "searchemail")
      if (!searchEmail.value.trim()) {
        alert("이메일을 입력하세요.");
        return;
      }

      try {
        // Call Vuex action to get user data
        const userData = await store.dispatch("getWodUserByEmail", { email: searchEmail.value, boxName: boxName.value});
        if (userData) {
          user.value = userData;
          users.value = [];
        } else {
          user.value = null;
          users.value = [];
          console.warn("⚠️ Warning: User document does not exist.");
          alert("해당 사용자를 찾을 수 없습니다.");
        }
      } catch (error) {
        console.error("❌ Error fetching user:", error);
        alert("사용자 검색 중 오류가 발생했습니다.");
      }
    };

    const searchUserByPhone = async () => {
      if (!searchPhone.value.trim()) {
        alert("전화번호를 입력하세요.");
        return;
      }

      try {
        // Call Vuex action to get user data
        const userData = await store.dispatch("getUserByPhone", { phone: searchPhone.value, boxName: boxName});
        if (userData) {
          user.value = userData;
          users.value = [];
        } else {
          user.value = null;
          users.value = [];
          console.warn("⚠️ Warning: User document does not exist.");
          alert("해당 사용자를 찾을 수 없습니다.");
        }
      } catch (error) {
        console.error("❌ Error fetching user:", error);
        alert("사용자 검색 중 오류가 발생했습니다.");
      }
    }

    const isClassMember = (targetUser) => {
      if (!targetUser?.email || !Array.isArray(props.classmembers)) return false;
      return props.classmembers.some(r => r.email === targetUser.email);
    };

    const showModal = (selectedClass, selectedDate) => {
    modalStatus.value = true
    classId.value = selectedClass
    date.value = selectedDate
    }

    const checkApprovalRequestModal = (result) => {
      modalStatus.value = false
      emit('approvalRequestModalResult', result)
    }


    const addMember = (targetUser) => {
      if (!wodConfirmationModalRef.value || !targetUser) return;
      wodConfirmationModalRef.value.showModal(
        targetUser,
        classId.value,
        date.value
      );
    };

    return {
      modalStatus,
      activeTab,
      searchName,
      searchEmail,
      searchPhone,
      setActiveTab,
      getAge,
      getGender,
      searchUserByName,
      searchUserByEmail,
      searchUserByPhone,
      isClassMember,
      user,
      users,
      showModal,
      checkApprovalRequestModal,
      addMember,
      wodConfirmationModalRef,
      classId,
      date,
    };
  },
};
</script>

<style scoped>
.search-container {
  display: flex;
  gap: -50px;
  margin-bottom: 20px;
}

.search-input {
  flex: 1;
}

.search-button {
  white-space: nowrap;
}

.modal-header {
  background-color: rgb(70, 100, 200);
  color: #ffffff;
}

.modal-title {
  color: var(--cui-white)
}
</style>

// react_web_app/src/components/modals/class/AddReserveMemberModal.tsx
import React, { useState } from 'react';
import { Search, User, Mail, Phone, UserPlus, X } from 'lucide-react';
import { Gradients } from '../../../constants/gradients';
import { AppColors } from '../../../constants/colors';
import { MemberService } from '../../../services/memberService';

interface AddReserveMemberModalProps {
  visible: boolean;
  onClose: () => void;
  onAddMember: (member: UserData) => void;
  reservedMembers: string[];
  boxName: string;
}

interface UserData {
  email: string;
  realName: string;
  nickName: string;
  phone: string;
}

type TabType = 'realName' | 'email' | 'phone';

const AddReserveMemberModal = ({
  visible,
  onClose,
  onAddMember,
  reservedMembers,
  boxName
}: AddReserveMemberModalProps) => {
  const [activeTab, setActiveTab] = useState<TabType>('realName');
  const [searchName, setSearchName] = useState('');
  const [searchEmail, setSearchEmail] = useState('');
  const [searchPhone, setSearchPhone] = useState('');
  const [user, setUser] = useState<UserData | null>(null);
  const [users, setUsers] = useState<UserData[]>([]);
  const [isSearching, setIsSearching] = useState(false);

  const resetSearch = () => {
    setUser(null);
    setUsers([]);
    setSearchName('');
    setSearchEmail('');
    setSearchPhone('');
  };

  const setActiveTabHandler = (tab: TabType) => {
    setActiveTab(tab);
    resetSearch();
  };

  const searchUserByName = async () => {
    if (!searchName.trim()) {
      alert('이름을 입력하세요.');
      return;
    }

    setIsSearching(true);
    try {
      const userData = await MemberService.getUserByRealName(searchName.trim());
      if (userData && userData.length > 0) {
        setUsers(userData);
        setUser(null);
      } else {
        setUsers([]);
        setUser(null);
        alert('해당 사용자를 찾을 수 없습니다.');
      }
    } catch (error) {
      console.error('Error fetching user:', error);
      alert('사용자 검색 중 오류가 발생했습니다.');
    } finally {
      setIsSearching(false);
    }
  };

  const searchUserByEmail = async () => {
    if (!searchEmail.trim()) {
      alert('이메일을 입력하세요.');
      return;
    }

    setIsSearching(true);
    try {
      const userData = await MemberService.getUserByEmail(searchEmail.trim());
      if (userData) {
        setUser(userData);
        setUsers([]);
      } else {
        setUser(null);
        setUsers([]);
        alert('해당 사용자를 찾을 수 없습니다.');
      }
    } catch (error) {
      console.error('Error fetching user:', error);
      alert('사용자 검색 중 오류가 발생했습니다.');
    } finally {
      setIsSearching(false);
    }
  };

  const searchUserByPhone = async () => {
    if (!searchPhone.trim()) {
      alert('전화번호를 입력하세요.');
      return;
    }

    setIsSearching(true);
    try {
      const userData = await MemberService.getUserByPhone(searchPhone.trim());
      if (userData) {
        setUser(userData);
        setUsers([]);
      } else {
        setUser(null);
        setUsers([]);
        alert('해당 사용자를 찾을 수 없습니다.');
      }
    } catch (error) {
      console.error('Error fetching user:', error);
      alert('사용자 검색 중 오류가 발생했습니다.');
    } finally {
      setIsSearching(false);
    }
  };

  const isClassMember = (targetUser: UserData) => {
    if (!targetUser?.email || !Array.isArray(reservedMembers)) return false;
    return reservedMembers.some(r => r.includes(targetUser.email));
  };

  const handleAddMember = (targetUser: UserData) => {
    if (isClassMember(targetUser)) {
      alert('이미 추가된 회원입니다.');
      return;
    }
    onAddMember(targetUser);
    handleClose();
  };

  const handleClose = () => {
    resetSearch();
    onClose();
  };

  const handleKeyPress = (e: React.KeyboardEvent, searchFn: () => void) => {
    if (e.key === 'Enter') {
      searchFn();
    }
  };

  if (!visible) return null;

  const renderUserCard = (targetUser: UserData, index?: number) => {
    const alreadyAdded = isClassMember(targetUser);

    return (
      <div key={index ?? 'single'} className="user-card">
        <div className="user-card-header">
          <User size={20} className="user-icon" />
          <span className="card-title">검색 결과</span>
        </div>
        <div className="user-card-body">
          <div className="user-info-row">
            <strong>이름:</strong>
            <span>{targetUser.realName}</span>
            {alreadyAdded && <span className="badge-added">이미 추가된 회원</span>}
          </div>
          <div className="user-info-row">
            <strong>연락처:</strong>
            <span>{targetUser.phone}</span>
          </div>
          <div className="user-info-row">
            <strong>이메일:</strong>
            <span>{targetUser.email}</span>
          </div>
        </div>
        <div className="user-card-footer">
          <button
            className="btn btn-success"
            onClick={() => handleAddMember(targetUser)}
            disabled={alreadyAdded}
          >
            <UserPlus size={16} />
            추가
          </button>
        </div>
      </div>
    );
  };

  return (
    <div className="modal-overlay" onClick={handleClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <div className="header-title">
            <UserPlus size={20} className="header-icon" />
            <h3>회원 추가</h3>
          </div>
          <button className="close-button" onClick={handleClose}>
            <X size={20} />
          </button>
        </div>

        <div className="modal-body">
          {/* 탭 네비게이션 */}
          <div className="tabs">
            <button
              className={`tab-button ${activeTab === 'realName' ? 'active' : ''}`}
              onClick={() => setActiveTabHandler('realName')}
            >
              <User size={16} />
              이름으로 찾기
            </button>
            <button
              className={`tab-button ${activeTab === 'email' ? 'active' : ''}`}
              onClick={() => setActiveTabHandler('email')}
            >
              <Mail size={16} />
              이메일로 찾기
            </button>
            <button
              className={`tab-button ${activeTab === 'phone' ? 'active' : ''}`}
              onClick={() => setActiveTabHandler('phone')}
            >
              <Phone size={16} />
              전화번호로 찾기
            </button>
          </div>

          {/* 탭 컨텐츠 */}
          <div className="tab-content">
            {/* 이름 검색 탭 */}
            {activeTab === 'realName' && (
              <div className="search-row">
                <label>이름</label>
                <input
                  type="text"
                  value={searchName}
                  onChange={(e) => setSearchName(e.target.value)}
                  onKeyPress={(e) => handleKeyPress(e, searchUserByName)}
                  placeholder="이름을 입력하세요."
                  disabled={isSearching}
                />
                <button
                  className="btn btn-primary"
                  onClick={searchUserByName}
                  disabled={isSearching}
                >
                  <Search size={16} />
                  검색
                </button>
              </div>
            )}

            {/* 이메일 검색 탭 */}
            {activeTab === 'email' && (
              <div className="search-row">
                <label>이메일</label>
                <input
                  type="text"
                  value={searchEmail}
                  onChange={(e) => setSearchEmail(e.target.value)}
                  onKeyPress={(e) => handleKeyPress(e, searchUserByEmail)}
                  placeholder="이메일을 입력하세요."
                  disabled={isSearching}
                />
                <button
                  className="btn btn-primary"
                  onClick={searchUserByEmail}
                  disabled={isSearching}
                >
                  <Search size={16} />
                  검색
                </button>
              </div>
            )}

            {/* 전화번호 검색 탭 */}
            {activeTab === 'phone' && (
              <div className="search-row">
                <label>전화번호</label>
                <input
                  type="text"
                  value={searchPhone}
                  onChange={(e) => setSearchPhone(e.target.value)}
                  onKeyPress={(e) => handleKeyPress(e, searchUserByPhone)}
                  placeholder="핸드폰 번호를 입력하세요.(- 제외)"
                  disabled={isSearching}
                />
                <button
                  className="btn btn-primary"
                  onClick={searchUserByPhone}
                  disabled={isSearching}
                >
                  <Search size={16} />
                  검색
                </button>
              </div>
            )}
          </div>

          {/* 검색 결과 영역 */}
          <div className="results-area">
            {/* 단일 사용자 */}
            {user && renderUserCard(user)}

            {/* 여러 사용자 */}
            {users.length > 0 && (
              <div className="users-grid">
                {users.map((u, index) => renderUserCard(u, index))}
              </div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={handleClose}>
            닫기
          </button>
        </div>
      </div>

      <style>{`
        .modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background-color: rgba(0, 0, 0, 0.5);
          display: flex;
          justify-content: center;
          align-items: center;
          z-index: 1001;
        }

        .modal-content {
          background: white;
          border-radius: 12px;
          box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);
          width: 90%;
          max-width: 600px;
          max-height: 90vh;
          overflow-y: auto;
          animation: modalSlideIn 0.2s ease-out;
        }

        @keyframes modalSlideIn {
          from {
            opacity: 0;
            transform: translateY(-20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        .modal-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 20px;
          background: ${Gradients.primary};
          border-bottom: none;
          border-radius: 12px 12px 0 0;
          box-shadow: 0 2px 10px rgba(102, 126, 234, 0.15);
        }

        .header-title {
          display: flex;
          align-items: center;
          gap: 10px;
        }

        .header-icon {
          color: white;
          opacity: 0.9;
        }

        .modal-header h3 {
          margin: 0;
          font-size: 1.25rem;
          font-weight: 600;
          color: white;
        }

        .close-button {
          background: none;
          border: none;
          cursor: pointer;
          color: white;
          opacity: 0.8;
          padding: 4px;
          width: 32px;
          height: 32px;
          display: flex;
          align-items: center;
          justify-content: center;
          border-radius: 50%;
          transition: all 0.2s;
        }

        .close-button:hover {
          background-color: rgba(255, 255, 255, 0.2);
          opacity: 1;
          transform: scale(1.1);
        }

        .modal-body {
          padding: 24px;
        }

        .tabs {
          display: flex;
          gap: 8px;
          margin-bottom: 20px;
          border-bottom: 2px solid #e5e7eb;
        }

        .tab-button {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 10px 16px;
          border: none;
          background: transparent;
          color: #6b7280;
          font-weight: 500;
          cursor: pointer;
          border-bottom: 2px solid transparent;
          margin-bottom: -2px;
          transition: all 0.2s;
        }

        .tab-button:hover {
          color: ${AppColors.primary};
          background-color: rgba(102, 126, 234, 0.05);
        }

        .tab-button.active {
          color: ${AppColors.primary};
          border-bottom-color: ${AppColors.primary};
        }

        .tab-content {
          margin-bottom: 24px;
        }

        .search-row {
          display: grid;
          grid-template-columns: 80px 1fr auto;
          gap: 12px;
          align-items: center;
        }

        .search-row label {
          font-weight: 500;
          color: #374151;
          font-size: 14px;
        }

        .search-row input {
          padding: 10px 12px;
          border: 1px solid #d1d5db;
          border-radius: 6px;
          font-size: 14px;
          transition: border-color 0.2s ease, box-shadow 0.2s ease;
        }

        .search-row input:focus {
          outline: none;
          border-color: ${AppColors.primary};
          box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
        }

        .search-row input:disabled {
          background-color: #f3f4f6;
          cursor: not-allowed;
        }

        .results-area {
          min-height: 100px;
        }

        .users-grid {
          display: grid;
          gap: 16px;
        }

        .user-card {
          border: 1px solid #e5e7eb;
          border-radius: 8px;
          overflow: hidden;
          background: white;
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
          transition: all 0.2s ease;
        }

        .user-card:hover {
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
          transform: translateY(-1px);
        }

        .user-card-header {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 12px 16px;
          background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
          border-bottom: 1px solid #e5e7eb;
        }

        .user-icon {
          color: ${AppColors.primary};
        }

        .card-title {
          font-weight: 600;
          color: #1f2937;
          font-size: 14px;
        }

        .user-card-body {
          padding: 16px;
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .user-info-row {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 14px;
        }

        .user-info-row strong {
          min-width: 60px;
          color: #6b7280;
          font-weight: 500;
        }

        .user-info-row span {
          color: #1f2937;
        }

        .badge-added {
          background: #fef3c7;
          color: #92400e;
          padding: 2px 8px;
          border-radius: 12px;
          font-size: 12px;
          font-weight: 600;
          margin-left: auto;
        }

        .user-card-footer {
          padding: 12px 16px;
          background: #f9fafb;
          border-top: 1px solid #e5e7eb;
          display: flex;
          justify-content: flex-end;
        }

        .modal-footer {
          display: flex;
          justify-content: flex-end;
          padding: 20px;
          border-top: 1px solid #e5e7eb;
          background-color: #f9fafb;
        }

        .btn {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 8px 16px;
          border-radius: 6px;
          border: 1px solid;
          cursor: pointer;
          font-weight: 500;
          font-size: 14px;
          transition: all 0.2s;
        }

        .btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .btn-primary {
          background-color: ${AppColors.primary};
          border-color: ${AppColors.primary};
          color: white;
        }

        .btn-primary:hover:not(:disabled) {
          background-color: #4f63d7;
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(102, 126, 234, 0.3);
        }

        .btn-secondary {
          background-color: #ffffff;
          border-color: #d1d5db;
          color: #374151;
        }

        .btn-secondary:hover {
          background-color: #f9fafb;
          border-color: #9ca3af;
        }

        .btn-success {
          background-color: #10b981;
          border-color: #10b981;
          color: white;
        }

        .btn-success:hover:not(:disabled) {
          background-color: #059669;
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(16, 185, 129, 0.3);
        }

        .btn-success:disabled {
          background-color: #d1d5db;
          border-color: #d1d5db;
        }
      `}</style>
    </div>
  );
};

export default AddReserveMemberModal;
